import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>SnapApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>SnapApp</h1>
      <p>ゆうてまだ全然完成してない</p>
      <Link href="/app/auth">ログイン / 新規登録</Link>
      <div>
        <ul>
          <Link href="https://snapapp-webclient.vercel.app/">
            <li>安定バージョン(公開バージョン)</li>
          </Link>
          <Link href="https://snapapp-webclient-git-nightly-tamagoez.vercel.app/">
            <li>nightlyバージョン(準公開バージョン)</li>
          </Link>
          <Link href="https://d25fr1-3000.preview.csb.app/">
            <li>real-timeバージョン(不安定/最新バージョン)</li>
          </Link>
        </ul>
      </div>
    </>
  );
}
